---
- hosts: workstations
  become: true
  handlers:
    - name: Restart snapd
      systemd:
          name: snapd
          state: restarted
  tasks:
    - name: Text-based packages on workstations
      when: ansible_distribution == "Debian"
      apt:
          name:
              - devscripts
              - build-essential
              - ccache
              - cmake
              - clang
              - diffoscope
              - gist
              - manpages-dev
              - lintian
              - snapd
              - vim-youcompleteme
              - links2
              - elinks
              - nlohmann-json3-dev
              - distro-info
              - mutt
              - valgrind
              - sshfs
              - minicom
              - bundler
              - ocrmypdf
    - name: Debian development etc.
      when: ansible_distribution == "Debian"
      apt:
        name:
          - devscripts
          - cowbuilder
    - name: GUI utilities, not AV/media
      when: ansible_distribution == "Debian"
      apt:
          name:
              - vim-gtk
              - wireshark
              - gitk
              - i3-wm
              - i3lock
              - i3status
              - thunderbird
              - firefox-esr
              - chromium
              - scrot
              - speedcrunch
              - suckless-tools
              - xserver-xorg
              - lightdm
              - xss-lock
              - xvnc4viewer
              - xfonts-terminus
              - xserver-xorg-input-synaptics
              - xinput
              - xsel
              - feh
              - kdiff3
              - xvfb
    - name: LaTeX and related tools
      when: ansible_distribution == "Debian"
      apt:
        name:
          - texlive-full
          - gummi
          - comparepdf
          - diffpdf
          - evince
    - name: freerdp2 from backports
      apt:
        name: freerdp2-x11=2.3.*
    - name: Install core snap
      snap:
          name: core
          channel: stable
      notify: Restart snapd
    - name: Flush handlers
      meta: flush_handlers
    - name: Install signal
      snap:
          name: signal-desktop
          channel: stable
    - name: Install kerberos
      apt:
          name: krb5-user
          state: present
    - name: Set krb5 config
      copy:
          src: files/kerberos/krb5.conf
          dest: /etc/
          owner: root
          mode: 0644
