---
- hosts: all
  become: true
  tasks:
      - name: ensure directory exists
        file:
            path: /etc/chromium/policies/managed
            state: directory
            owner: root
            group: root
            mode: '0755'
      - name: create policy file
        copy:
            src: files/chrome/managed_policies.json
            dest: /etc/chromium/policies/managed/managed_policies.json
            owner: root
            group: root
            mode: '0644'
            validate: jq . '%s'
      - name: create compatibility symlink
        file:
            path: /etc/opt/chrome
            state: link
            src: /etc/chromium
