---
- hosts: workstations
  become: true
  handlers:
    - name: Restart snapd
      systemd:
          name: snapd
          state: restarted
  tasks:
    - name: Text-based packages on workstations
      when: ansible_distribution == "Debian"
      apt:
          name:
              - devscripts
              - build-essential
              - cmake
              - clang
              - diffoscope
              - gist
              - manpages-dev
              - lintian
              - snapd
    - name: GUI utilities, not AV/media
      when: ansible_distribution == "Debian"
      apt:
          name:
              - vim-gtk
              - wireshark
              - gitk
              - i3-wm
              - i3lock
              - i3status
              - thunderbird
              - firefox-esr
              - chromium
              - scrot
              - speedcrunch
              - suckless-tools
              - xserver-xorg
              - lightdm
              - xss-lock
              - xvnc4viewer
              - xfonts-terminus
              - xserver-xorg-input-synaptics
              - xinput
              - xsel
              - feh
    - name: Install core snap
      snap:
          name: core
          channel: stable
      notify: Restart snapd
    - name: Flush handlers
      meta: flush_handlers
    - name: Install signal
      snap:
          name: signal-desktop
          channel: stable
    - name: Install kerberos
      apt:
          name: krb5-user
          state: present
    - name: Set krb5 config
      copy:
          src: files/kerberos/krb5.conf
          dest: /etc/
          owner: root
          mode: 0644
