---
- hosts: workstations
  become: true
  tasks:
    - name: Text-based packages on workstations
      when: ansible_distribution == "Debian"
      apt:
          name:
              - devscripts
              - build-essential
              - cmake
              - clang
              - diffoscope
              - gist
              - manpages-dev
              - lintian
    - name: GUI utilities, not AV/media
      when: ansible_distribution == "Debian"
      apt:
          name:
              - vim-gtk
              - wireshark
              - gitk
              - i3-wm
              - i3lock
              - i3status
              - thunderbird
              - firefox-esr
              - chromium
              - scrot
              - speedcrunch
              - suckless-tools
              - xserver-xorg
              - lightdm
              - xss-lock
              - xvnc4viewer
              - xfonts-terminus
              - xserver-xorg-input-synaptics
              - xinput
    - name: Games
      when: ansible_distribution == "Debian" # and gui
      apt:
          name:
              - sgt-puzzles
