all:
    children:
        workstations:
            hosts:
                debsilent:
                debwork.hq.code-worms.com:
                    debian_codename: buster
        av:
            hosts:
                debwork.hq.code-worms.com:
                debsilent:
                deblap65:
        games:
            hosts:
                debsilent:
                deblap65:
        intelvideo:
            hosts:
                debsilent:
                deblap65:
                debwork.hq.code-worms.com:
